<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Assets/Scripts/Common.Editor/**/*.cs" Link="Common.Editor/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.7.3" />
    <PackageReference Include="Unity3D.UnityEngine" Version="2018.3.5.1" />
    <PackageReference Include="Unity3D.UnityEngine.UI" Version="2018.3.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
	<ProjectReference Include="..\Common.Unity\Common.Unity.csproj" />
  </ItemGroup>
  
	<ItemGroup>
	  <Reference Include="Unity.TextMeshPro">
		<HintPath>../dll/Unity.TextMeshPro.dll</HintPath>
	  </Reference>
	</ItemGroup>
	
	<ItemGroup>
	  <Reference Include="LeanTween">
		<HintPath>../dll/LeanTween.dll</HintPath>
	  </Reference>
	</ItemGroup>
	
	<ItemGroup>
	  <Reference Include="UnityEditor">
		<HintPath>C:\Program Files\Unity\Hub\Editor\6000.0.44f1\Editor\Data\Managed\UnityEditor.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
